### ISSUE TITLE
Assets/Standard Assets/Cameras/Scripts/TargetFieldOfView.cs(62,53): error CS0246: The type or namespace name 'ParticleRenderer' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by raoping2017** [udacity/self-driving-car-sim#104]
Assets/Standard Assets/Cameras/Scripts/TargetFieldOfView.cs(62,53): error CS0246: The type or namespace name 'ParticleRenderer' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ICEBERG-VR** [comment]
Same pb here after migrating a project from 2018.2 to 2018.3

**Comment by YiheChen1995** [comment]
Same problem. Any Idea how this happened?

**Comment by daxiao** [comment]
Same problem

**Comment by xooxo** [comment]
It is because Unity removed all functionality of API regarding ParticleRenderer.

**Comment by Stormwaker** [comment]
Just use Unity 2018.2 for this project. Anything newer will cause this error to appear.

**Comment by marianpekar** [comment]
As @xooxo said, ParticleRenderer has been removed. ParticleSystem is need to be used instead.
https://docs.unity3d.com/ScriptReference/ParticleSystem.html

**Comment by marianpekar** [comment]
As @xooxo said, ParticleRenderer has been removed. ParticleSystemRenderer is need to be used instead.
https://docs.unity3d.com/ScriptReference/ParticleSystemRenderer.html

**Comment by MrGT07** [comment]
Just remove that part of the code from the OR condition and it would still works the same as the ParticleRenderer returns "true" anyway.
